AUTOVENTAS_Cars/Controllers/CuentaController.cs
using AUTOVENTAS_Cars.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AUTOVENTAS_Cars.Controllers
{
    public class CuentaController : Controller
    {

        public DB_AUTOVENTAS db = new DB_AUTOVENTAS();
        
        // GET: Cuenta
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Usuario usuario)
        {
            var usr = db.usuario.FirstOrDefault(u => u.correo == usuario.correo && u.contraseña==usuario.contraseña);
            if (usr != null)
            {
                Session["nombreUsuario"] = usr.nombre;
                Session["idUsuario"] = usr.idUsuario;
                return VerificarSesion();
            }
            else {
                ModelState.AddModelError("", "Usuario o contraseña incorrecta");
            }
            return View();
        }



        public ActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrar(Usuario usuario)
        {
            if (ModelState.IsValid) {
                Rol rol = db.rol.FirstOrDefault(r => r.idRol==2);
                usuario.rol = rol;
                db.usuario.Add(usuario);
                db.SaveChanges();
                ViewBag.mensaje = "El usuario " + usuario + "fue registrado exitosamente";
                ModelState.Clear();
            }
            return View();
        }

        public ActionResult VerificarSesion()
        {
            if (Session["idUsuario"].Equals(2))
            {
                return RedirectToAction("../Home/Index");

            }
            else if(Session["idUsuario"].Equals(1))
            {
                return RedirectToAction("../Home/NoDisponible");
            }
            else {
                return RedirectToAction("Login");
            }
        }

        public ActionResult Logout()
        {
            Session.Remove("IDUsuario");
            Session.Remove("nombreUsuario");
            return RedirectToAction("Login");
        }
    }
}   

AUTOVENTAS_Cars/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AUTOVENTAS_Cars.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NoDisponible()
        {
            return View();
        }
    }
}

AUTOVENTAS_Cars/Views/Home/Index.cshtml
@{
    ViewBag.Title = "DASHBOARD";
}


@if (Session["nombreUsuario"] != null)
{
    <h2>Bienvenido @Session["nombreUsuario"]</h2>
    <div class="page-header">
        <h1><small>Panel de administración</small></h1>
    </div>
    <div class="row">
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="@Url.Content("~/Imagenes/chevrolet1.jpg")" alt="...">
                    <div class="caption">
                        <h3>Ingreso de vehiculos</h3>
                        <p>Aqui puede ingresar todos los vehiculos nuevos al stock </p>
                        <p>@Html.ActionLink("Agregar Vehiculos", "RegistrarVehiculo", "Vehiculo", null, htmlAttributes: new { @class = "btn btn-primary" })</p>
                    </div>
                </div>
            </div>            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="@Url.Content("~/Imagenes/hyundai1.jpg")" alt="...">
                    <div class="caption">
                        <h3>Listado de Vehiculos</h3>
                        <p>Aqui pude visualizar el catálogo de vehiculos disponibles</p>
                        <p>@Html.ActionLink("Listado de Vehiculos", "ListarVehiculo", "Vehiculo", null, htmlAttributes: new { @class = "btn btn-primary" })</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="@Url.Content("~/Imagenes/kia1.jpg")" alt="...">
                    <div class="caption">
                        <h3>Eliminar vehiculos</h3>
                        <p>Aqui puede eliminar los vehiculos que desee</p>
                        <p>@Html.ActionLink("Eliminar Vehiculos", "ListarVehiculo", "Vehiculo", null, htmlAttributes: new { @class = "btn btn-primary" })</p>
                    </div>
                </div>
            </div> 
    </div>
}

else {
    <h2> Por favor inicie sesion </h2>
    <li> @Html.ActionLink("Registrarse", "Registrar", "Cuenta") </li>
    <li> @Html.ActionLink("Iniciar Sesion", "Login", "Cuenta") </li>
}

AUTOVENTAS_Cars/Views/Home/NoDisponible.cshtml
@{
    ViewBag.Title = "DASHBOARD";
}

<body>
    @if (Session["nombreUsuario"] != null)
    {
        <h2>Bienvenido @Session["nombreUsuario"], lamentamos las molestias pero este sitio aun esta en construccion</h2>
        <h1>Pronto estara habilitado</h1>


        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Auto Ventas Car's", "NoDisponible", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>
                    @if (Session["IDUsuario"] != null)
                {
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li>@Html.ActionLink("Inicio", "NoDisponible", "Home")</li>
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="a" role="button" aria-haspopup="true" aria-expanded="false">
                                        @Session["nombreUsuario"] <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Logout", "Logout", "Cuenta")</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </div>

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>



    }

    else {
        <h2> Por favor inicie sesion </h2>
        <li> @Html.ActionLink("Registrarse", "Registrar", "Cuenta") </li>
        <li> @Html.ActionLink("Iniciar Sesion", "Login", "Cuenta") </li>
    }

</body>